#!/bin/bash

# Compute and plot the order of convergence depending on the choice
# of cell width dx.

# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=


genparamfile() {
    # generate parameter file.
    # $1 = nx
    # $2 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nsteps = 1000"   >> $f
    echo "nx = $1"          >> $f
    echo "tmax = 0"         >> $f
    echo "foutput = 0"      >> $f
    echo "dt_out = 0"       >> $f
    echo "nstep_log = 100"  >> $f
    echo "basename = $2"    >> $f
    echo "ccfl = 0.3"       >> $f
    echo "boundary = 2"     >> $f
}



icfile=$ICDIR/sod_test.dat


# start with high nx so the wave structure won't be out of the boundary at tmax
for nx in 5000 10000 20000 50000 80000 100000; do

    for RIEMANN in EXACT TSRS TRRS HLLC; do
        genparamfile $nx GODUNOV-"$RIEMANN"-"$nx"
        $EXECDIR/hydro-godunov-$RIEMANN-1D paramfile.txt $icfile | tee -a output.log
    done
done

$EVALDIR/godunov-1D-convergence-dx.py $icfile
