#!/bin/bash

# Compute and plot the order of convergence depending on the choice
# of time step dt.
# Don't forget that you need to your highest value to be already for a very low Ccfl number!

# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=


genparamfile() {
    # generate parameter file.
    # $1 = dt
    # $2 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nsteps = 200000"   >> $f
    echo "nx = 500"         >> $f
    echo "tmax = 0"         >> $f
    echo "foutput = 0"      >> $f
    echo "dt_out = 0"       >> $f
    echo "nstep_log = 10000" >> $f
    echo "force_dt = $1"    >> $f
    echo "basename = $2"    >> $f
    echo "boundary = 2"     >> $f
}



icfile=$ICDIR/sod_test.dat

for dt in 0.000001 0.0000008 0.0000006 0.0000004 0.0000002 0.0000001; do

    dtform=`printf %.12f $dt`

    for RIEMANN in EXACT TSRS TRRS HLLC; do
        genparamfile $dt GODUNOV-"$RIEMANN"-"$dtform"
        $EXECDIR/hydro-godunov-$RIEMANN-1D paramfile.txt $icfile | tee -a output.log
    done
done

$EVALDIR/godunov-1D-convergence-dt.py $icfile
