#!/bin/bash

# Run an exact and approximate solvers on a set of Riemann problems and despair.
# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=


genparamfile() {
    # generate parameter file.
    # $1 = tmax
    # $2 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nx = 500"         >> $f
    echo "tmax = $1"        >> $f
    echo "basename = $2"    >> $f
}



fnames=( left_blast_wave.dat  right_blast_wave.dat  sod_test.dat  sod_test_modified.dat )
tmaxes=( 0.05 0.05 0.20 0.20 )

for ((i=0; i<4; i++)) do
    
    fname=${fnames[i]}
    tmax=${tmaxes[i]}

    icfile=$ICDIR/$fname

    for RIEMANN in EXACT TSRS TRRS; do
        genparamfile $tmax ${fname%.dat}-"$RIEMANN"
        $EXECDIR/riemann-$RIEMANN paramfile.txt $icfile | tee -a output.log
    done

    $EVALDIR/riemann-1D-overplot-approximate-solvers.py $fname
done
