#!/bin/bash

# Compute and plot the order of convergence depending on the choice
# of cell size dx, i.e. on the choice of the number of cells nx.

# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=



genparamfile() {
    # generate parameter file.
    # $1 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nsteps = 10000"    >> $f
    echo "tmax = 0"         >> $f
    echo "foutput = 0"      >> $f
    echo "dt_out = 0"       >> $f
    echo "basename = $1"    >> $f
    echo "ccfl = 0.9"       >> $f
    echo "nstep_log = 1000"  >> $f
}



for shape in step gaussian; do

    for nx in 100 200 500 800 1000 1500 2000 ; do

        icfile=$ICDIR/advection-1D-$shape-$nx.dat

        for limiter in MC MINMOD SUPERBEE VANLEER; do
            genparamfile ADVECTION_PWLIN-"$limiter"-"$shape"-"$nx"
            $EXECDIR/hydro-advection-$limiter-1D paramfile.txt $icfile | tee -a output.log
        done

        genparamfile ADVECTION_PWLIN-"NO_LIMITER"-"$shape"-"$nx"
        $EXECDIR/hydro-ADVECTION_PWLIN-1D paramfile.txt $icfile | tee -a output.log

        genparamfile ADVECTION_PWCONST-"$shape"-"$nx"
        $EXECDIR/execs/hydro-ADVECTION_PWCONST-1D paramfile.txt $icfile | tee -a output.log

    done
    $EVALDIR/advection-1D-convergence-dx.py $shape

done
