#!/bin/bash

# Compute and plot the order of convergence depending on the choice
# of time step dt.
# Don't forget that you need to your highest value to be already for a very low Ccfl number!

# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=


genparamfile() {
    # generate parameter file.
    # $1 = dt
    # $2 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nsteps = 10000"   >> $f
    echo "tmax = 0"         >> $f
    echo "foutput = 0"      >> $f
    echo "dt_out = 0"       >> $f
    echo "nstep_log = 1000" >> $f
    echo "force_dt = $1"    >> $f
    echo "basename = $2"    >> $f
}



for shape in step gaussian; do

    for nx in 500; do

        icfile=$ICDIR/advection-1D-$shape-$nx.dat

        for dt in 0.0002 0.0001 0.00009 0.00007 0.00005 0.00003 0.00001; do

            dtform=`printf %.8f $dt`

            for limiter in MC MINMOD SUPERBEE VANLEER; do
                genparamfile $dt ADVECTION_PWLIN-"$limiter"-"$dtform"-$shape-$nx
                $EXECDIR/hydro-advection-$limiter-1D paramfile.txt $icfile | tee -a output.log
            done

            genparamfile $dt ADVECTION_PWLIN-"NO_LIMITER"-"$dtform"-$shape-$nx
            $EXECDIR/hydro-ADVECTION_PWLIN-1D   paramfile.txt $icfile | tee -a output.log

            genparamfile $dt ADVECTION_PWCONST-"$dtform"-$shape-$nx
            $EXECDIR/hydro-ADVECTION_PWCONST-1D paramfile.txt $icfile | tee -a output.log

        done

        $EVALDIR/advection-1D-convergence-dt.py $shape $nx

    done

done
