#!/bin/bash

# Compute and plot the order of convergence depending on the choice
# of the Courant number Ccfl.

# you need to set following variables:
# 
# EXECDIR: the directory containing executables of the program created by the /program/bin/generate-all-execs.sh script
# ICDIR:   the directory containing the IC file you require
# EVALDIR: the directory containing python evaluation and plotting scripts, i.e. /py/evaluations
#
# you also need to prepare your own IC files. Scripts to do that are in /py/IC

EXECDIR=
ICDIR=
EVALDIR=


genparamfile() {
    # generate parameter file.
    # $1 = CFL
    # $2 = basename

    f=paramfile.txt
    echo "// parameter file for hydro program; generated by run.sh" > $f
    echo ""                 >> $f
    echo "verbose = 1"      >> $f
    echo "nsteps = 10000"   >> $f
    echo "tmax = 0"         >> $f
    echo "ccfl = $1"        >> $f
    echo "basename = $2"    >> $f
    echo "nstep_log = 1000"  >> $f
}



for shape in step gaussian; do

    for nx in 500 ; do

        icfile=$ICDIR/advection-1D-$shape-$nx.dat

        for ccfl in 0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1; do

            cflform=`printf %.8f $ccfl`

            for limiter in MC MINMOD SUPERBEE VANLEER; do
                genparamfile $ccfl ADVECTION_PWLIN-"$limiter"-$shape-"$cflform"
                $EXECDIR/hydro-ADVECTION_PWLIN-$limiter-1D paramfile.txt $icfile | tee -a output.log
            done

            genparamfile $ccfl ADVECTION_PWLIN-"NO_LIMITER"-$shape-"$cflform"
            $EXECDIR/hydro-ADVECTION_PWLIN-1D paramfile.txt $icfile | tee -a output.log

            genparamfile $ccfl ADVECTION_PWCONST-$shape-"$cflform"
            $EXECDIR/hydro-ADVECTION_PWCONST-1D paramfile.txt $icfile | tee -a output.log

        done

    $EVALDIR/advection-1D-convergence-CCFL.py $shape

    done

done
