#!/usr/bin/env python3


# -------------------------------------------------
# Create an IC file from an output file
# generated by the hydro code
#
# usage:
#   output_to_IC.py outputfile.out
#
# resulting IC file will be called 'restart.dat'
# -------------------------------------------------


from mesh_hydro_utils import get_only_cmdlinearg
from mesh_hydro_io import read_output, write_ic
from mesh_hydro_plotting import plot_1D, plot_2D


# plotting parameters
dots = False  # overplot dots on 1D plot


if __name__ == "__main__":
    fname = get_only_cmdlinearg()
    ndim, rho, u, p, t = read_output(fname)
    write_ic("restart.dat", ndim, rho, u, p)
